name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    # MYSQL 설정
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: utf8mb4
        mysql database: livear
        mysql user: ${{ secrets.RDS_USER }}
        mysql password: ${{ secrets.RDS_PASSWORD }}
    - uses : actions/checkout@v3

     #1
    # application.properties는 외부에 노출되면 안되므로 Actions가 빌드될때마다 해당 Repository의 Secret 설정을
    - run : touch ./src/main/resources/application.properties
    - run : echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
    - run : cat ./src/main/resources/application.properties

    # gradlew에 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # gradlew 빌드
    - name: Build with Gradle
      run: ./gradlew clean build

    # 빌드를 성공하면 해당 프로젝트를 zip로 만듬
    - name: Make zip file
      run: zip -r ./LIVEAR_SERVER.zip .
      shell: bash

    #2
    # AWS 계정 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
      # 깃허브 Secret에 넣어둔 Access key
        aws-access-key-id: ${{ secrets.S3_IAM_ACCESSKEY }}
      # 깃허브 Secret에 넣어둔 Secret key
        aws-secret-access-key: ${{ secrets.S3_IAM_SECRETKEY }}
      # 깃허브 Secret에 넣어둔 Region
        aws-region: ${{ secrets.AWS_REGION }}

    #3
    # 만들어 놓은 S3에 해당 zip 파일 저장
    - name: Upload to S3
      run: aws s3 cp ./LIVEAR_SERVER.zip s3://livear-github-action-s3-bucket/LIVEAR_SERVER.zip

    #4
    # AWS CodeDeploy에 배포
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_IAM_ACCESSKEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_IAM_SECRETKEY }}
      run: |
        aws deploy create-deployment \
        --application-name CodeDeploy-app \
        --deployment-group-name CodeDeploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=livear-github-action-s3-bucket,bundleType=zip,key=LIVEAR_SERVER.zip \
        --region ${{ secrets.AWS_REGION }}
